name: deploy website
on:
  push:
    branches: '*'
  workflow_dispatch:

permissions:
  id-token: write
  pages: write

jobs:
  build:
    name: building
    runs-on: ubuntu-latest

    steps:
      - name: clone
        uses: actions/checkout@v5

      - name: setup zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1

      - name: building zig
        run: |
          zig build -Dtarget=wasm32-freestanding

      - name: upload files
        uses: actions/upload-pages-artifact@v3
        with:
          path: zig-out/bin/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: deploy to gh pages
        uses: actions/deploy-pages@v4

