name: deploy website
on:
  push:
    branches: '*'
  workflow_dispatch:

jobs:
  build:
    name: building
    runs-on: ubuntu-latest

    steps:
      - name: build zig
      - uses: actions/checkout@v5
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1
      - run: |
          zig build -Dtarget=wasm32-freestanding

      - name: upload files
      - uses: actions/upload-pages-artifact@v3
        with:
          path: output/
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: deploy to gh pages
        uses: actions/deploy-pages@v4


